# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'iOS-Training-Networking2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks


  # Pods for iOS-Training-Networking2
	pod 'Alamofire', '~> 4.5'
  pod 'KeychainSwift', '~> 10.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
end
